- type: replace
  path: /releases/-
  value:
    name: gitlab-runner
    version: latest

- type: replace
  path: /instance_groups/-
  value:
    name: gitlab-runner
    instances: 1
    azs: [z1,z2,z3]
    jobs:
    - name: bpm
      release: bpm
    - name: docker
      release: gitlab-runner
      properties:
        tcp_address: 0.0.0.0
        tls_cacert: "((docker-tls.ca))"
        tls_cert: "((docker-tls.certificate))"
        tls_key: "((docker-tls.private_key))"
        env:
          http_proxy: ((http_proxy))
          https_proxy: ((https_proxy))
          no_proxy: ((no_proxy_str))
    - name: gitlab-runner
      release: gitlab-runner
      properties:
        runner:
          name: gitlab-runner
          tags:
            - large
            - vm
          registration:
            url: ((gitlab_url))
            token: ((gitlab_runner_token))
        env:
          http_proxy: ((http_proxy))
          https_proxy: ((https_proxy))
          no_proxy: ((no_proxy_str))
    networks:
    - default: [dns,gateway]
      name: default
    stemcell: default
    persistent_disk_type: 100GB
    vm_type: large

- type: replace
  path: /variables/-
  value:
    name: docker-ca
    type: certificate
    options:
      is_ca: true
      common_name: dockerCA

- type: replace
  path: /variables/-
  value:
    name: docker-tls
    type: certificate
    options:
      ca: docker-ca
      common_name: docker
      extended_key_usage:
        - client_auth
